* About

Hello! This is the repository for my cloud infrastructure and some personal
applications.

* Setup

** Secrets

Infrastructure related secrets are statically encrypted in the repository using
SOPS and are easily decrypted, and imported for CUE consumption as required.

#+begin_src shell :results none
cue decrypt github.com/augustfengd/augustfeng.app/secrets
cue convert github.com/augustfengd/augustfeng.app/secrets
#+end_src

Secrets that are specific to services can be just as prepared for usage:

#+begin_src shell :resultss none
cue decrypt github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
cue convert github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
#+end_src

** Building the pipelines

This project is nearly heavily automated using pipelines. The pipeline
configuration are coded with CUE and compiled using a variety of different
methods.

- cloud pipeline:

#+begin_src shell :results none
cue build github.com/augustfengd/augustfeng.app/cloud/pipeline
#+end_src

- blog pipeline:

#+begin_src shell :results none
cue pipeline github.com/augustfengd/augustfeng.app/apps/blog
#+end_src

- domain pipeline:

#+begin_src shell :results none
make -C apps/domain ../../.github/workflows/apps.domain.yaml
#+end_src

- toolchain pipeline:

#+begin_src shell :results none
cue cmd build github.com/augustfengd/augustfeng.app/apps/toolchain/pipeline
#+end_src

** Terraform

The terraform cloud project configuration is configured prior to the plan and
applies:

- configure the terraform workspace variables:

#+begin_src shell
  # if working from root directory.
  cue cmd configure github.com/augustfengd/augustfeng.app/cloud/terraform:augustfeng_app
#+end_src

- build, plan and apply:

#+begin_src shell
# for a better ux, we can run the commands directly from the package to typing the package's fqdn.
cd cloud/terraform

cue cmd build
cue cmd init
cue cmd plan
cue cmd apply
#+end_src

** Kubernetes

I have written some abstractions in CUE to easily author kubernetes
configuration. Additionally, there is also scripting layer to consumes the
configuration:

#+begin_src shell
# kubectl backend
cue cmd template github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
cue cmd diff github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
cue cmd apply github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik

# kubectl/helm backend
cue cmd template github.com/augustfengd/augustfeng.app/cloud/kubernetes/cert-manager # this project doesn't use cert-manager anymore though.
cue cmd diff github.com/augustfengd/augustfeng.app/cloud/kubernetes/cert-manager
cue cmd apply github.com/augustfengd/augustfeng.app/cloud/kubernetes/cert-manager
#+end_src
